"use client";

import { useEffect, useState } from "react";
import { OperationsShell } from "@/components/layout/OperationsShell";
import { useSelectedSeason } from "./use-selected-season";

type Prediction = { id: string; homeWinProb: number | string | null; drawProb: number | string | null; awayWinProb: number | string | null; expectedHomeGoals: number | string | null; expectedAwayGoals: number | string | null; confidence: number | string | null; predictedAt: string; modelVersion: { modelKey: string; version: string; status: string; featureSchemaVersion: string }; result: { actualOutcome: string; correct: boolean | null } | null; match: { kickoffAt: string | null; homeTeam: { canonicalName: string; shortName: string | null }; awayTeam: { canonicalName: string; shortName: string | null } } | null };
export function PredictionsPage() {
  const { seasons, seasonsLoading, seasonId, setSeasonId } = useSelectedSeason();
  const [predictions, setPredictions] = useState<Prediction[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!seasonId) return; setError(null); fetch(`/api/v1/predictions?seasonId=${encodeURIComponent(seasonId)}`, { credentials: "include" }).then(async (response) => { const body = await response.json() as { data?: Prediction[]; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Predictions unavailable."); setPredictions(body.data ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Predictions unavailable.")); }, [seasonId]);
  return <OperationsShell title="Prediction center" section="Predictions">
    <p className="page-lead">Persisted model outputs only. Every prediction includes its model version and feature schema; no probability is invented when a prediction record is absent.</p>
    <div className="page-toolbar"><label>Season<select className="season-select" value={seasonId} onChange={(event) => setSeasonId(event.target.value)}><option value="">{seasonsLoading ? "Discovering…" : "Select season"}</option>{seasons.map((season) => <option value={season.id} key={season.id}>{season.competition.canonicalName} · {season.name}</option>)}</select></label></div>
    {error && <div className="error-state compact-state"><div className="error-icon">!</div><div><h2>Prediction data unavailable</h2><p>{error}</p></div></div>}
    {!error && seasonId && predictions.length === 0 && <div className="empty-state"><div className="empty-icon">◌</div><div><h2>No persisted predictions</h2><p>Train and validate a model, then run the prediction refresh worker. The page intentionally does not generate placeholder probabilities.</p></div></div>}
    {!error && predictions.length > 0 && <section className="prediction-list">{predictions.map((prediction) => <article className="panel prediction-card" key={prediction.id}><div className="prediction-header"><div><p className="eyebrow">{prediction.modelVersion.modelKey} · {prediction.modelVersion.version}</p><h2>{prediction.match ? `${prediction.match.homeTeam.canonicalName} vs ${prediction.match.awayTeam.canonicalName}` : "Unresolved fixture"}</h2><span className="entity-id">{prediction.predictedAt} · {prediction.modelVersion.featureSchemaVersion}</span></div>{prediction.result && <span className={prediction.result.correct ? "result-good" : "result-bad"}>{prediction.result.correct ? "Correct" : "Evaluated"}</span>}</div><div className="probability-grid"><Probability label="Home" value={prediction.homeWinProb} accent="teal" /><Probability label="Draw" value={prediction.drawProb} accent="amber" /><Probability label="Away" value={prediction.awayWinProb} accent="blue" /></div><div className="prediction-foot"><span>Expected goals <b>{prediction.expectedHomeGoals ?? "—"} — {prediction.expectedAwayGoals ?? "—"}</b></span><span>Confidence <b>{prediction.confidence ?? "—"}</b></span><span>Status <b>{prediction.modelVersion.status}</b></span></div></article>)}</section>}
  </OperationsShell>;
}
function Probability({ label, value, accent }: { label: string; value: number | string | null; accent: string }) { const numeric = value === null ? 0 : Number(value); return <div className="probability-cell"><span>{label}</span><strong>{value === null ? "—" : `${Math.round(numeric * 100)}%`}</strong><i className={`probability-bar accent-${accent}`} style={{ width: `${Math.max(0, Math.min(100, numeric * 100))}%` }} /></div>; }
