"use client";

import { useEffect, useState } from "react";
import { OperationsShell } from "@/components/layout/OperationsShell";

type SecurityPayload = { data: { events: Array<{ id: string; type: string; severity: string; requestId: string | null; route: string | null; occurredAt: string }>; alerts: Array<{ id: string; title: string; description: string | null; severity: string; status: string; createdAt: string }>; snapshot: { capturedAt: string; totalRequests: number; errorRequests: number; errorRate: number | string; p95DurationMs: number; totalErrors: number; recentErrors: number } | null } };
export function SecurityPage() {
  const [payload, setPayload] = useState<SecurityPayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/v1/security/overview", { credentials: "include" }).then(async (response) => { const body = await response.json() as unknown; if (!response.ok) { const errorBody = body as { error?: { message?: string } }; throw new Error(errorBody.error?.message ?? "Security overview unavailable."); } setPayload(body as SecurityPayload); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Security overview unavailable.")); }, []);
  return <OperationsShell title="Security operations" section="Security">
    <p className="page-lead">Permission-controlled view of security events, open alerts, request health and durable observability samples. Sensitive metadata is not rendered here.</p>
    {error && <div className="error-state compact-state"><div className="error-icon">!</div><div><h2>Security data unavailable</h2><p>{error}</p></div></div>}
    {!error && !payload && <div className="loading-grid"><div className="skeleton skeleton-panel" /></div>}
    {payload && <><section className="metric-grid"><Metric label="Open alerts" value={payload.data.alerts.length} detail="Open or acknowledged" accent="amber" /><Metric label="Recent events" value={payload.data.events.length} detail="Latest 30 events" accent="teal" /><Metric label="Error rate" value={payload.data.snapshot ? String(payload.data.snapshot.errorRate) : "—"} detail="Latest durable snapshot" accent="danger" /><Metric label="p95 latency" value={payload.data.snapshot ? `${payload.data.snapshot.p95DurationMs}ms` : "—"} detail="Latest durable snapshot" accent="blue" /></section><section className="security-grid"><section className="panel page-panel"><div className="panel-header"><div><h2>Open alerts</h2><p>Review before resolution</p></div></div>{payload.data.alerts.length === 0 ? <div className="empty-inline">No open alerts.</div> : <div className="alert-list">{payload.data.alerts.map((alert) => <article className="alert-row" key={alert.id}><span className={`severity-dot severity-${alert.severity.toLowerCase()}`} /><div><strong>{alert.title}</strong><p>{alert.description ?? "No description provided."}</p></div><small>{alert.status}</small></article>)}</div>}</section><section className="panel page-panel"><div className="panel-header"><div><h2>Recent events</h2><p>Request IDs support investigation without exposing secrets</p></div></div><div className="table-wrap"><table><thead><tr><th>Type</th><th>Severity</th><th>Route</th><th>Request ID</th><th>Occurred</th></tr></thead><tbody>{payload.data.events.map((event) => <tr key={event.id}><td>{event.type}</td><td>{event.severity}</td><td>{event.route ?? "—"}</td><td className="entity-id">{event.requestId ?? "—"}</td><td>{new Date(event.occurredAt).toLocaleString()}</td></tr>)}</tbody></table></div></section></section></>}
  </OperationsShell>;
}
function Metric({ label, value, detail, accent }: { label: string; value: string | number; detail: string; accent: string }) { return <article className={`metric-card accent-${accent}`}><div className="metric-label">{label}</div><strong>{value}</strong><span className="metric-detail">{detail}</span></article>; }
